name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.124.172.98
          username: web_lite1
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/public_html/Litescaler
            git pull origin main
            npm install
            npm run build